name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: boilerplate_v4
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1
      DB_PORT: 32574
      REDIS_PORT: 6379
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplate_v4
    services:
      mariadb:
        image: mariadb:10.9
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: boilerplate_v4
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: ["8.1"]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run Migration
        run: php artisan migrate

      - name: Execute Pest tests
        run: vendor/bin/pest

      - name: Install Node dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          config: baseUrl=http://127.0.0.1:8000
          browser: chrome
